name: GWE2026

channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - xarray
  - dask
  - distributed
  - netcdf4
  - h5py
  - rasterio
  - cartopy
  - shapely
  - pyproj
  - satpy
  - pyresample
  - pyorbital
  - pyspectral
  - bokeh
